conduit/articles/urls.py
# Django
from django.urls import path

# Local
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.article_index, name="index"),
    path("follows/", views.article_index, name="follows", kwargs={"follows": True}),
    path("tag/<slug:tag>/", views.article_index, name="tag"),
    path(
        "comments/<int:comment_id>/~delete", views.delete_comment, name="delete_comment"
    ),
    path("~submit/", views.create_article, name="create"),
    path("<int:article_id>/~edit/", views.edit_article, name="edit"),
    path("<int:article_id>/~delete/", views.delete_article, name="delete"),
    path("<int:article_id>/~like/", views.like_article, name="like"),
    path("<slug:slug>/", views.article_detail, name="detail"),
]

conduit/users/urls.py
# Django
from django.urls import path

# Local
from . import views

app_name = "users"

urlpatterns = [
    path("<int:user_id>/~follow/", views.follow, name="follow"),
    path("<int:user_id>/~unfollow/", views.unfollow, name="unfollow"),
    path("settings/", views.user_settings, name="settings"),
    path(
        "<slug:username>/favories/",
        views.user_detail,
        name="favorites",
        kwargs={"favorites": True},
    ),
    path("<slug:username>/", views.user_detail, name="detail"),
]

conduit/articles/models.py
# Django
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.safestring import mark_safe

# Third Party Libraries
import markdown
from model_utils.models import TimeStampedModel
from taggit.managers import TaggableManager


class ArticleQuerySet(models.QuerySet):
    def with_num_likes(self):
        return self.annotate(num_likes=models.Count("likers"))


class ArticleManager(models.Manager.from_queryset(ArticleQuerySet)):
    ...


class Article(TimeStampedModel):
    slug = models.SlugField(max_length=255, unique=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    body = models.TextField()

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    tags = TaggableManager()

    objects = ArticleManager()

    class Meta:
        indexes = [
            models.Index(fields=["slug"]),
            models.Index(fields=["created", "-created"]),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("articles:detail", args=[self.slug])

    def as_markdown(self):
        return mark_safe(markdown.markdown(self.body))


class Comment(TimeStampedModel):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    body = models.TextField()

    class Meta:
        indexes = [
            models.Index(fields=["created", "-created"]),
        ]

    def as_markdown(self):
        return mark_safe(markdown.markdown(self.body))

conduit/articles/forms.py
# Django
from django import forms

# Local
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ("slug", "title", "description", "body", "tags")
        labels = {
            "title": "Article Title",
            "description": "What's this article about?",
            "slug": "Article URL",
            "body": "Write your article (in Markdown)",
        }
        widgets = {"description": forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["tags"].required = False


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("body",)
        labels = {"body": "Write a comment..."}

conduit/articles/views.py
# Django
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.views.decorators.http import require_POST

# Third Party Libraries
from taggit.models import TaggedItem

# Conduit
from conduit.common.turbo import render_turbo_stream
from conduit.common.turbo.response import (
    TurboStreamResponse,
    TurboStreamStreamingResponse,
    TurboStreamTemplateResponse,
)

# Local
from .forms import ArticleForm, CommentForm
from .models import Article, Comment


def article_index(request, follows=False, tag=None):
    """Show list of articles"""

    articles = (
        Article.objects.with_num_likes().select_related("author").order_by("-created")
    )

    tags = (
        TaggedItem.objects.select_related("tag")
        .values_list("tag__slug", "tag__name")
        .distinct()
    )

    if tag:
        articles = articles.filter(tags__slug__in=[tag])

    if follows and request.user.is_authenticated:
        articles = articles.filter(author__in=request.user.follows.all())

    return TemplateResponse(
        request,
        "articles/index.html",
        {"articles": articles, "tags": tags, "follows": follows, "tag": tag,},
    )


def article_detail(request, slug):

    article = get_object_or_404(
        Article.objects.with_num_likes().select_related("author"), slug=slug,
    )

    comment_form = None

    if request.user.is_authenticated:
        if request.method == "POST":
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.author = request.user
                comment.article = article
                comment.save()
                messages.success(request, "Your comment has been posted")
            return redirect(article)
        else:
            comment_form = CommentForm()

    comments = article.comment_set.select_related("author").order_by("-created")

    is_following = (
        request.user.is_authenticated
        and article.author.followers.filter(pk=request.user.id).exists()
    )

    can_follow = can_like = (
        request.user.is_authenticated and request.user != article.author
    )

    can_edit = request.user.is_authenticated and request.user == article.author

    return TemplateResponse(
        request,
        "articles/detail.html",
        {
            "article": article,
            "comment_form": comment_form,
            "comments": comments,
            "is_following": is_following,
            "can_follow": can_follow,
            "can_like": can_like,
            "can_edit": can_edit,
        },
    )


@login_required
def create_article(request):
    if request.method == "POST":
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.save()
            # save tags
            form.save_m2m()
            messages.success(request, "Your article has been published!")
            return redirect("articles:index")
        return TurboStreamTemplateResponse(
            request,
            "articles/_article_form.html",
            {"form": form},
            target="article-form",
            action="update",
        )
    else:
        form = ArticleForm()
    return TemplateResponse(request, "articles/article_form.html", {"form": form})


@login_required
def edit_article(request, article_id):
    article = get_object_or_404(Article, author=request.user, pk=article_id)
    if request.method == "POST":
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            article = form.save()
            messages.success(request, "Your article has been updated")
            return redirect(article)
        return TurboStreamTemplateResponse(
            request,
            "articles/_article_form.html",
            {"form": form},
            target="article-form",
            action="update",
        )
    else:
        form = ArticleForm(instance=article)
    return TemplateResponse(
        request, "articles/article_form.html", {"form": form, "article": article}
    )


@login_required
@require_POST
def like_article(request, article_id):
    article = get_object_or_404(
        Article.objects.exclude(author=request.user), pk=article_id
    )

    if request.user.likes.filter(pk=article_id).exists():
        request.user.likes.remove(article)
    else:
        request.user.likes.add(article)

    num_likes = article.likers.count()

    def render_likes():

        for target in [
            f"article-likes-{article.id}",
            "article-likes-header",
            "article-likes-body",
        ]:
            yield render_turbo_stream(target=target, action="update", content=num_likes)

    return TurboStreamStreamingResponse(render_likes())


@login_required
@require_POST
def delete_article(request, article_id):
    article = get_object_or_404(Article, author=request.user, pk=article_id)
    article.delete()
    messages.info(request, "Your article has been deleted")
    return redirect("articles:index")


@login_required
@require_POST
def delete_comment(request, comment_id):
    comment = get_object_or_404(
        Comment.objects.select_related("article", "author"),
        author=request.user,
        pk=comment_id,
    )
    comment.delete()
    return TurboStreamResponse(action="remove", target=f"comment-{comment_id}")

templates/articles/_article.html
<div class="border-b pb-3 mb-3" id="article-{{ article.id }}">
  <div class="flex items-center justify-between mb-3">
    <div class="">
      <div class="flex items-center mb-1">
        {% include "users/_avatar.html" with user=article.author size="32" css_class="mr-2" %}
        <a
          class="font-semibold text-lg text-blue-800 hover:text-blue-600"
          href="{{ article.author.get_absolute_url }}"
          >{{ article.author }}</a
        >
      </div>
      <div class="text-gray-500 text-sm">{{ article.created|date }}</div>
    </div>

    {% if request.user.is_authenticated and request.user != article.author %}
    {% include "articles/_like.html" with num_likes=article.num_likes can_like=True %}
    {% else %}
    {% include "articles/_like.html" with num_likes=article.num_likes can_like=False %}
    {% endif %}
  </div>
  <div class="mb-3">
    <div class="text-xl font-bold mb-1">
      {{ article.title }}
    </div>
    <div class="text-sm text-gray-500 mb-3">
      {{ article.description|truncatechars:100 }}
    </div>
    <a
      href="{{ article.get_absolute_url }}"
      class="text-sm text-blue-800 hover:text-blue-600"
      >Read more...</a
    >
  </div>
</div>

templates/articles/_article_form.html
{% load widget_tweaks %}
<form
  data-controller="slugify"
  class="rounded border bg-white mb-3"
  method="post"
  action="{{ request.path }}"
  novalidate
>
  {% include "_form_errors.html" with errors=form.non_field_errors %} {% csrf_token %}
  {% with WIDGET_ERROR_CLASS="form-input-error" widget_class="form-input text-lg p-2 w-full" %}
  <div class="p-3 mb-3">
    <div class="mb-3">
      {% render_field form.title|set_data:"action:keyup->slugify#slugify" class=widget_class placeholder=form.title.label %}
      {% include "_form_errors.html" with errors=form.title.errors %}
    </div>
    <div class="mb-3">
      <div class="flex items-center">
        <div class="font-semibold text-gray-500 text-lg mr-1">
          http://{{ request.site.domain }}/
        </div>
        {% render_field form.slug|set_data:"slugify-target:field" class=widget_class placeholder=form.slug.label %}
      </div>
      {% include "_form_errors.html" with errors=form.slug.errors %}
    </div>
    <div class="mb-3">
      {% render_field form.description class=widget_class placeholder=form.description.label %}
      {% include "_form_errors.html" with errors=form.description.errors %}
    </div>
    <div class="mb-3">
      {% render_field form.body class=widget_class placeholder=form.body.label %}
      {% include "_form_errors.html" with errors=form.body.errors %}
    </div>
    <div>
      {% render_field form.tags class=widget_class placeholder=form.tags.label %}
      {% include "_form_errors.html" with errors=form.tags.errors %}
    </div>
  </div>
  {% endwith %}
  <div
    class="flex bg-gray-100 rounded-b-lg border border-t-none p-3 justify-end items-center"
  >
    {% if article %}
    <a
      class="text-blue-800 hover:text-blue-600 mr-3 text-lg"
      href="{{ article.get_absolute_url }}"
      >Cancel</a
    >
    <button
      type="submit"
      class="px-4 py-2 rounded bg-blue-800 text-white hover:bg-blue-600"
    >
      Save Article
    </button>
    {% else %}
    <button
      type="submit"
      class="px-4 py-2 rounded bg-blue-800 text-white hover:bg-blue-600"
    >
      Publish Article
    </button>
    {% endif %}
  </div>
</form>

templates/articles/_detail_like.html
{% extends "articles/_like.html" %} {% block target %}{% endblock %} {% block counter %}
<i class="fa fa-heart mr-1"></i> Favorite Article (<span id="{{ dom_id }}">{% include "articles/_likes_counter.html" %}</span>) {% endblock %}

templates/articles/_like.html
{% if can_like %}
<form method="post" action="{% url 'articles:like' article.id %}">
  {% csrf_token %} {% block target %}
  <input type="hidden" name="target" value="article-likes-{{ article.id }}" />
  {% endblock %} {% endif %}
  <button
    class="rounded border p-2 text-sm {% if can_like %}hover:bg-gray-100{% else %}cursor-default{% endif %} focus:outline-none"
  >
    {% block counter %}
    <i class="fa fa-heart mr-1"></i>
    <span id="article-likes-{{ article.id }}"
      >{% include "articles/_likes_counter.html" %}</span
    >
    {% endblock %}
  </button>
  {% if can_like %}
</form>
{% endif %}

templates/articles/_likes_counter.html
{{ num_likes|default:0 }}

templates/articles/article_form.html
{% extends "base.html" %} {% load widget_tweaks %} {% block content %}
<div class="flex justify-center items-center">
  <div class="w-full lg:w-2/3" id="article-form">
    {% include "articles/_article_form.html" %}
  </div>
</div>

{% endblock content %}

templates/articles/author.html
{% extends "base.html" %}
{% block header %}
{{ block.super }}
<div class="flex justify-center text-center items-center py-6 mb-3 mx-auto bg-gradient-to-b from-indigo-900 to-indigo-700 text-white w-full">
  <div>
    <h1 class="text-5xl mb-6">{{ author.username }}</h1>
    <div class="">
      <button class="rounded px-4 py-2 border hover:bg-indigo-300">
        <i class="fa fa-plus mr-1"></i> Follow {{ article.author }}
      </button>
    </div>
  </div>
</div>
{% endblock header %}


{% block content %}
{% for article in articles.object_list %}
{% include "articles/_article.html" %}
{% endfor %}
{% include "_pagination.html" with page_obj=articles %}
{% endblock content %}

templates/articles/detail.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load pagination %}

{% block header %}
{{ block.super }}
<div class="py-6 mx-auto px-3 md:px-12 mb-3 mx-auto bg-gradient-to-b from-indigo-900 to-indigo-700 text-white w-full">
  <h1 class="text-2xl font-bold mb-3">{{ article.title }}</h1>
  <h2 class="text-lg mb-3">{{ article.description }}</h2>
  <div class="md:flex justify-center items-center mb-3">

    <div class="mb-6 md:mr-6 md:mb-0">
      <div class="flex items-center mb-1">
        {% include "users/_avatar.html" with user=article.author size="32" css_class="mr-2" %}
        <a class="font-semibold text-lg hover:text-gray-100"
           href="{{ article.author.get_absolute_url }}">{{ article.author }}</a>
      </div>
      <div class="text-sm">{{ article.created|date }}</div>
    </div>

    {% if can_edit %}
    <div class="mb-6 md:mb-0 md:mr-6">
      <a class="rounded px-4 py-2 border hover:bg-indigo-300"
         href="{% url 'articles:edit' article.id %}">
        <i class="fa fa-pen mr-1"></i> Edit Article
      </a>
    </div>
    <form action="{% url 'articles:delete' article.id %}"
          method="post">
      {% csrf_token %}
      <button class="rounded px-4 py-2 border hover:bg-indigo-300"
              data-controller="confirm"
              data-confirm-text-value="Are you sure you want to delete this article?"
              data-action="confirm#confirm">
        <i class="fa fa-trash mr-1"></i> Delete Article
      </button>
    </form>
    {% endif %}

    {% if can_follow %}
    <div class="mb-3 md:mr-6 md:mb-0" id="follow-header">
      {% include "users/_follow.html" with user_obj=article.author %}
    </div>
    {% endif %}

    {% if can_like %}
    <div class="md:mr-6">
      {% include "articles/_detail_like.html" with num_likes=article.num_likes dom_id="article-likes-header" %}
    </div>
    {% endif %}
  </div>

</div>
{% endblock header %}

{% block content %}
<div class="pb-6 border-b mb-3">
  <p>
    {{ article.as_markdown }}
  </p>
</div>

<div class="md:flex justify-center items-center mb-3">

  <div class="mb-3 md:mr-6 md:mb-0">
    <div class="flex items-center mb-1">
      {% include "users/_avatar.html" with user=article.author size="32" css_class="mr-2" %}
      <a class="font-semibold text-lg text-blue-800 hover:text-blue-600"
         href="">{{ article.author }}</a>
    </div>
    <div class="text-gray-500 text-sm">{{ article.created|date }}</div>
  </div>

  {% if can_follow %}
  <div class="mb-3 md:mr-6 md:mb-0" id="follow-body">
    {% include "users/_follow.html" with user_obj=article.author %}
  </div>
  {% endif %}

  {% if can_like %}
  <div>
    {% include "articles/_detail_like.html" with num_likes=article.num_likes dom_id="article-likes-body" %}
  </div>
  {% endif %}

  {% if can_edit %}
  <div class="mb-6 md:mb-0 md:mr-6">
    <a class="rounded px-4 py-2 border hover:bg-gray-300"
       href="{% url 'articles:edit' article.id %}">
      <i class="fa fa-pen mr-1"></i> Edit Article
    </a>
  </div>
  <form action="{% url 'articles:delete' article.id %}"
        method="post">
    {% csrf_token %}
    <button class="rounded px-4 py-2 border border-red-500 text-red-500 hover:bg-red-300"
            data-controller="confirm"
            data-confirm-text-value="Are you sure you want to delete this article?"
            data-action="confirm#confirm">
      <i class="fa fa-trash mr-1"></i> Delete Article
  </form>
  {% endif %}
</div>

<div class="flex justify-center">
  <div class="w-full lg:w-3/4">

    {% if comment_form %}
    <form method="post"
          class="bg-gray-100 w-full mb-3 rounded border"
          action="{{ request.path }}">
      {% csrf_token %}
      {% with WIDGET_ERROR_CLASS="text-red-800" widget_class="appearance-none text-lg rounded-t-lg p-3 pb-0 border border-gray-300 w-full h-64" %}
      <div class="">
        {% render_field comment_form.body class=widget_class placeholder=comment_form.body.label %}
        {% include "_form_errors.html" with errors=comment_form.body.errors %}
      </div>
      {% endwith %}
      <div class="flex justify-end p-3">
        <button type="submit"
                class="px-4 py-2 rounded bg-blue-800 text-white hover:bg-blue-600">Submit Comment</button>
      </div>
    </form>
    {% endif %}

    {% paginate comments as page_obj %}
    {% for comment in page_obj.object_list %}
    <div class="border rounded mb-3"
         id="comment-{{ comment.id }}">
      <div class="p-3">{{ comment.as_markdown }}</div>

      <div class="bg-gray-100 p-3 flex items-center justify-between">
        <div class="flex items-center">
          <a href="{{ comment.author.get_absolute_url }}"
             class="mr-2 text-blue-800 hover:text-blue-600">{{ comment.author }}</a>
          <span class="text-sm text-gray-600">
            {{ comment.created|date }}
          </span>
        </div>
        {% if user == comment.author %}
        <form method="post"
              action="{% url 'articles:delete_comment' comment.id %}">
          {% csrf_token %}
          <button class="hover:text-gray-500"
                  data-controller="confirm"
                  data-confirm-text-value="Are you sure you want to delete this comment?"
                  data-action="confirm#confirm">
            <i class="fa fa-trash"></i>
          </button>
        </form>
        {% endif %}

      </div>

    </div>
    {% endfor %}
    {% include "_pagination.html" %}
  </div>
</div>
{% endblock content %}

templates/articles/index.html
{% extends "base.html" %}
{% load pagination %}
{% block header %}
{{ block.super }}
<div class="flex justify-center text-center items-center py-6 mb-3 mx-auto bg-gradient-to-b from-indigo-900 to-indigo-700 text-white w-full">
  <div>
    <h1 class="text-5xl mb-6">Conduit</h1>
    <p class="text-2xl">A place to share your knowledge.</p>
  </div>
</div>
{% endblock header %}

{% block content %}
<div class="md:grid grid-cols-3 gap-4">

  <div class="col-span-2">
    {% if user.is_authenticated and not tag %}
    <div class="border-b flex items-center mb-3">
      <a href="{% url 'articles:follows' %}"
         class="{% if follows %}text-blue-800 pb-3 border-b-2 border-blue-800{% else %}text-gray-500 hover:text-blue-800 pb-3{% endif %} mr-6">
        Your Feed
      </a>
      <a href="{% url 'articles:index' %}"
         class="{% if follows %}text-gray-500 hover:text-blue-800 pb-3{% else %}text-blue-800 pb-3 border-b-2 border-blue-800{% endif %}">
        Global Feed
      </a>
    </div>
    {% endif %}
    {% paginate articles as page_obj %}
    {% for article in page_obj.object_list %}
    {% include "articles/_article.html" %}
    {% endfor %}
    {% include "_pagination.html" %}
  </div>

  {% if tags %}
  <div class="col-span-1">
    <h2 class="text-lg mb-3 font-semibold">Popular tags</h2>
    <div class="p-3 rounded border">
      {% for slug, name in tags %}
      {% if slug == tag %}
      <span class="inline-block px-4 py-1 bg-indigo-800 text-white rounded mr-2 mb-1">#{{ name }}</span>
      {% else %}
      <a href="{% url 'articles:tag' slug %}"
         class="inline-block px-4 py-1 bg-gray-100 rounded mr-2 mb-1">#{{ name }}</a>
      {% endif %}
      {% endfor %}
    </div>
  </div>
  {% endif %}

</div>
{% endblock content %}