conduit/articles/urls.py
# Django
from django.urls import path

# Local
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.article_index, name="index"),
    path("follows/", views.article_index, name="follows", kwargs={"follows": True}),
    path("tag/<slug:tag>/", views.article_index, name="tag"),
    path(
        "comments/<int:comment_id>/~delete", views.delete_comment, name="delete_comment"
    ),
    path("~submit/", views.create_article, name="create"),
    path("<int:article_id>/~edit/", views.edit_article, name="edit"),
    path("<int:article_id>/~delete/", views.delete_article, name="delete"),
    path("<int:article_id>/~like/", views.like_article, name="like"),
    path("<slug:slug>/", views.article_detail, name="detail"),
]

conduit/users/urls.py
# Django
from django.urls import path

# Local
from . import views

app_name = "users"

urlpatterns = [
    path("<int:user_id>/~follow/", views.follow, name="follow"),
    path("<int:user_id>/~unfollow/", views.unfollow, name="unfollow"),
    path("settings/", views.user_settings, name="settings"),
    path(
        "<slug:username>/favories/",
        views.user_detail,
        name="favorites",
        kwargs={"favorites": True},
    ),
    path("<slug:username>/", views.user_detail, name="detail"),
]

templates/403_csrf.html
{% extends "error_base.html" %}
{% load i18n %}
{% block content %}
<p class="mb-3">
  {% trans "Sorry, there's been a problem posting your form. Please reload this page and try again." %}
</p>
<p class="">
  <a class="btn btn-primary"
     href="{{ request.get_full_path }}">{% trans "Reload Page" %}</a>
</p>
{% endblock %}

templates/405.html
{% extends "error_base.html" %}
{% load i18n %}
{% block content %}
<h1 class="page-header">{% trans "Not Allowed" %}</h1>
<p>
  {% trans "Sorry, you cannot perform this action. You may have disabled JavaScript on your browser or are using an older browser that does not support this action." %}
</p>
{% endblock %}

templates/_cookie_notice.html
{% load i18n %} {% if not accept_cookies %}
<form
  class="text-white bg-gray-800 w-full py-3 flex justify-center"
  id="accept-cookies"
  method="post"
  action="{% url 'accept_cookies' %}"
>
  {% csrf_token %}
  <div class="px-2">
    <div class="md:flex items-center">
      <p class="mb-3 md:mb-0 md:mr-4">
        {% blocktranslate %}This site uses cookies to ensure you get the best
        experience.{% endblocktranslate %}
        <a
          href="https://www.internetcookies.org/"
          target="_blank"
          rel="noopener noreferrer"
          class="font-semibold text-white"
          >{% translate "Learn more" %}</a
        >
      </p>
      <div class="text-center md:text-start">
        <button
          class="bg-blue-800 hover:bg-blue-600 text-white px-4 p-1 border border-white w-full sm:w-auto"
        >
          {% translate "Got it!" %}
        </button>
      </div>
    </div>
  </div>
</form>
{% endif %}

templates/_fontawesome.html
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
      integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="
      crossorigin="" />

templates/_footer.html
<footer class="p-2 mt-4 text-center bg-gray-900 text-gray-100 text-sm">
 &copy; Dan Jacob {% now "Y" %}
</footer

templates/_form_errors.html
{% if errors %}
<ul class="text-red-800 px-1">
  {% for error in errors %}
  <li class="my-3">
    {{ error }}
  </li>
  {% endfor %}
</ul>
{% endif %}

templates/_messages.html
{% if messages %}
<div class="flex justify-center">
  {% for message in messages %}
  <div
    data-controller="notification"
    data-notification-timeout-value="3000"
    class="fixed z-50 w-4/5 lg:w-1/3 flex items-center p-3 rounded shadow-xl mt-3 message {{ message.tags }}"
  >
    <div class="mx-auto text-center">{{ message }}</div>
    <button data-action="notification#remove" class="float-right">
      <i class="fa fa-times-circle"></i>
    </button>
  </div>
  {% endfor %}
</div>
{% endif %}

templates/_pagination.html
{% load i18n %}
{% load pagination %}
{% if page_obj.has_other_pages %}
<div class="text-sm flex justify-between {{ css_class|default:"mt-2" }}">
  <a {% if page_obj.has_previous %}
     class="block text-indigo-900 hover:text-indigo-700"
     href="{% pagination_url page_obj.previous_page_number %}"
     {% else %}
     class="text-gray-500 pointer-events-none"
     href="javascript:void(0);"
     {% endif %}>
    {% trans "Previous" %}
  </a>
  <a {% if page_obj.has_next %}
     href="{% pagination_url page_obj.next_page_number %}"
     class="block text-indigo-900 hover:text-indigo-700"
     {% else %}
     href="javascript:void(0);"
     class="text-gray-500 pointer-events-none"
     {% endif %}>
    {% trans "Next" %}
  </a>
</div>
{% endif %}

templates/_static.html
{% load static %}
<link rel="icon" type="image/png" href="{% static 'img/wave.png' %}" />
<link rel="apple-touch-icon image_src" href="{% static 'apple-touch-icon.png' %}" />
<link
  rel="stylesheet"
  data-turbo-track="reload"
  href="{% static debug|yesno:'dev/app.css,dist/app.css' %}"
/>
<script
  src="{% static debug|yesno:'dev/app.js,dist/app.js' %}"
  data-turbo-track="reload"
></script>

templates/base.html
{% spaceless %} {% load static %} {% load i18n %} {% endspaceless %}

<!DOCTYPE html>
{% get_current_language as language_code %}
<html lang="{{ language_code }}">
  <head>
    <title>
      {% spaceless %}{% block title %}Conduit{% endblock %}{% endspaceless %}
    </title>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="turbo-cache-control" content="no-cache" />
    <meta name="copyright" content="Dan Jacob {% now "Y" %}">
    <meta name="robots" content="index,follow" />

    {% include "_static.html" %} {% include "_fontawesome.html" %}
  </head>

  <body class="h-screen container-lg mx-auto antialiased bg-white">
    {% block header %}

    <header class="border-b pb-1 bg-gray-100">
      <div class="md:flex items-center justify-between p-2 md:px-12">
        <div class="flex items-center flex-shrink-0 mr-6 text-xl">
          <a class="text-indigo-900 font-bold" href="{% url 'articles:index' %}"
            >Conduit</a
          >
        </div>

        {% if user.is_authenticated %}
        <div>
          <a href="{% url 'articles:create' %}" class="inline-block mr-3">
            <i class="fa fa-pen mr-1"></i>
            New Article
          </a>

          <a href="{% url 'users:settings' %}" class="inline-block mr-3">
            <i class="fa fa-cog mr-1"></i>
            Settings
          </a>
          <form method="post" action="{% url 'account_logout' %}" class="inline-block">
            {% csrf_token %}
            <button class="">{% translate "Logout" %}</button>
          </form>
        </div>
        {% else %}
        <div>
          <a href="{% url 'account_login' %}" class="inline-block mr-3"
            >{% trans "Login" %}</a
          >
          <a href="{% url 'account_signup' %}" class="inline-block"
            >{% trans "Signup" %}</a
          >
        </div>
        {% endif %}
      </div>
    </header>
    {% include "_messages.html" %} {% include "_cookie_notice.html" %} {% endblock header %}

    <div class="min-h-full mx-auto p-2 pt-6 md:px-12 bg-white">
      {% block content %}{% endblock %}
    </div>
    {% include "_footer.html" %}
  </body>
</html>

templates/error_base.html
{% load static %} {% load i18n %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% trans "Error" %}</title>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="turbo-cache-control" content="no-cache" />
    {% include "_static.html" %} {% include "_fontawesome.html" %}
  </head>

  <body class="h-screen container-lg mx-auto antialiased">
    <header
      class="bg-gradient-to-b from-indigo-900 to-indigo-700 text-white p-2 md:px-5 mb-6"
    >
      <a href="/" class="text-xl tracking-tight text-white hover:text-gray-100"
        >{% trans "Home" %}</a
      >
    </header>
    <div class="h-full">
      <div
        class="border border-gray-500 mx-auto p-1 md:p-5 w-5/6 md:w-3/4 align-middle text-center"
      >
        {% block content %}{% endblock %}
      </div>
    </div>
    {% include "_footer.html" %}
  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
Welcome to the site!
{% endblock content %}