conduit/users/urls.py
# Django
from django.urls import path

# Local
from . import views

app_name = "users"

urlpatterns = [
    path("<int:user_id>/~follow/", views.follow, name="follow"),
    path("<int:user_id>/~unfollow/", views.unfollow, name="unfollow"),
    path("settings/", views.user_settings, name="settings"),
    path(
        "<slug:username>/favories/",
        views.user_detail,
        name="favorites",
        kwargs={"favorites": True},
    ),
    path("<slug:username>/", views.user_detail, name="detail"),
]

conduit/users/models.py
# Django
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

# Third Party Libraries
from sorl.thumbnail import ImageField


class UserQuerySet(models.QuerySet):
    def for_email(self, email):
        """Returns users matching this email address, including both
        primary and secondary email addresses

        Args:
            email (str): email address

        Returns:
            QuerySet
        """
        return self.filter(
            models.Q(emailaddress__email__iexact=email) | models.Q(email__iexact=email)
        )

    def matches_usernames(self, names):
        """Returns users matching the (case insensitive) username.

        Args:
            names (list): list of usernames

        Returns:
            QuerySet
        """
        if not names:
            return self.none()
        return self.filter(username__iregex=r"^(%s)+" % "|".join(names))


class UserManager(BaseUserManager.from_queryset(UserQuerySet)):
    def create_user(self, username, email, password=None, **kwargs):
        user = self.model(
            username=username, email=self.normalize_email(email), **kwargs
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password, **kwargs):
        return self.create_user(
            username, email, password, is_staff=True, is_superuser=True, **kwargs,
        )


class User(AbstractUser):
    name = models.CharField(_("Full name"), blank=True, max_length=255)

    bio = models.TextField(blank=True)
    image = ImageField(null=True, blank=True)

    follows = models.ManyToManyField(
        "self", related_name="followers", symmetrical=False, blank=True
    )

    likes = models.ManyToManyField(
        "articles.Article", related_name="likers", blank=True
    )

    objects = UserManager()

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("users:detail", args=[self.username])

    def get_email_addresses(self):
        """Get set of emails belonging to user.

        Returns:
            set: set of email addresses
        """
        return set([self.email]) | set(
            self.emailaddress_set.values_list("email", flat=True)
        )

conduit/users/forms.py
# Django
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm as BaseUserChangeForm
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm

# Third Party Libraries
from allauth.account.adapter import get_adapter
from allauth.account.forms import PasswordField, PasswordVerificationMixin

User = get_user_model()


class UserChangeForm(BaseUserChangeForm):
    class Meta(BaseUserChangeForm.Meta):
        model = User


class UserCreationForm(BaseUserCreationForm):
    class Meta(BaseUserCreationForm.Meta):
        model = User


class UserForm(PasswordVerificationMixin, forms.ModelForm):

    password1 = PasswordField(label="New Password", required=False)
    password2 = PasswordField(label="New Password (again)", required=False)

    class Meta:
        model = User
        fields = ("name", "image", "bio", "email")

    def clean_password1(self):
        password = self.cleaned_data.get("password1")
        if password:
            get_adapter().clean_password(password, self.instance)
        return password

    def save(self):
        instance = super().save(commit=False)
        password = self.cleaned_data.get("password1")
        if password:
            get_adapter().set_password(instance, password)
        else:
            instance.save()
        return instance

conduit/users/views.py
# Standard Library
import datetime

# Django
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils import timezone
from django.views.decorators.http import require_POST

# Conduit
from conduit.articles.models import Article
from conduit.common.turbo import render_turbo_stream_template_to_string
from conduit.common.turbo.response import (
    TurboStreamResponse,
    TurboStreamStreamingResponse,
    TurboStreamTemplateResponse,
)

# Local
from .forms import UserForm


def user_detail(request, username, favorites=False):

    user = get_object_or_404(get_user_model(), username=username)

    is_following = (
        request.user.is_authenticated
        and user.followers.filter(pk=request.user.id).exists()
    )

    can_follow = request.user.is_authenticated and request.user != user

    articles = (
        Article.objects.filter(author=user)
        .with_num_likes()
        .select_related("author")
        .order_by("-created")
    )

    if favorites:
        articles = articles.filter(num_likes__gt=0)

    return TemplateResponse(
        request,
        "users/detail.html",
        {
            "user_obj": user,
            "can_follow": can_follow,
            "is_following": is_following,
            "favorites": favorites,
            "articles": articles,
        },
    )


@login_required
def user_settings(request):
    if request.method == "POST":
        form = UserForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, "Your settings have been saved")
            return redirect(settings.HOME_URL)
        return TurboStreamTemplateResponse(
            request,
            "users/_settings_form.html",
            {"form": form},
            target="settings-form",
            action="update",
        )
    else:
        form = UserForm(instance=request.user)
    return TemplateResponse(request, "users/settings.html", {"form": form})


@login_required
@require_POST
def follow(request, user_id):
    user = get_object_or_404(
        get_user_model().objects.exclude(pk=request.user.id), pk=user_id
    )
    request.user.follows.add(user)
    return render_follows_response(request, user, is_following=True)


@login_required
@require_POST
def unfollow(request, user_id):
    user = get_object_or_404(request.user.follows.all(), pk=user_id)
    request.user.follows.remove(user)
    return render_follows_response(request, user, is_following=False)


@require_POST
def accept_cookies(request):
    response = TurboStreamResponse(action="remove", target="accept-cookies")
    response.set_cookie(
        "accept-cookies",
        value="true",
        expires=timezone.now() + datetime.timedelta(days=30),
        samesite="Lax",
    )
    return response


def render_follows_response(request, user, is_following):

    context = {"user_obj": user, "is_following": is_following}

    def render():
        for target in [
            "follow-header",
            "follow-body",
        ]:
            yield render_turbo_stream_template_to_string(
                "users/_follow.html",
                context,
                target=target,
                action="update",
                request=request,
            )

    return TurboStreamStreamingResponse(render())

templates/users/_avatar.html
{% load thumbnail account static %}
{% with thumbnail_size=size|default:"32" %}
{% thumbnail user.image thumbnail_size|add:"x"|add:thumbnail_size format="PNG" crop="center" as avatar %}
{% user_display user as username %}
<img src="{{ avatar.url }}"
     width="{{ avatar.width }}"
     height="{{ avatar.height }}"
     alt="{{ username }}"
     class="bg-transparent rounded-full {{ css_class }}">
{% empty %}
<img src="{% static 'img/smiley-cyrus.jpg' %}"
     alt="{{ username }}"
     height="{{ thumbnail_size }}"
     width="{{ thumbnail_size }}"
     class="bg-transparent rounded-full {{ css_class }}">
{% endthumbnail %}
{% endwith %}

templates/users/_follow.html
<form
  method="post"
  action="{% if is_following %}{% url 'users:unfollow' user_obj.id %}{% else %}{% url 'users:follow' user_obj.id %}{% endif %}">
  {% csrf_token %}
  {% if is_following %}
  <button class="rounded px-4 py-2 border hover:bg-indigo-300">
    <i class="fa fa-plus mr-1"></i> Unfollow {{ article.author }}
  </button>
  {% else %}
  <button class="rounded px-4 py-2 border hover:bg-indigo-300">
    <i class="fa fa-plus mr-1"></i> Follow {{ article.author }}
  </button>
  {% endif %}
</form>

templates/users/_settings_form.html
{% load widget_tweaks %}
<form
  class="rounded border bg-white mb-3 {% if form.errors %} border-red-800{% endif %}"
  method="post"
  enctype="multipart/form-data"
  novalidate
  action="{{ request.path }}"
>
  {% if form.errors %}
  <p class="p-3 text-center text-red-800">
    Your form contains some errors.
  </p>
  {% endif %} {% include "_form_errors.html" with errors=form.non_field_errors %} {%
  csrf_token %} {% with WIDGET_ERROR_CLASS="form-input-error" widget_class="form-input
  text-lg p-2 w-full" %}
  <div class="p-3 mb-3">
    <div class="mb-3">
      {% render_field form.name class=widget_class placeholder=form.name.label %} {%
      include "_form_errors.html" with errors=form.name.errors %}
    </div>
    <div class="mb-3">
      <label
        for="{{ form.image.id_for_label }}"
        class="block mb-2 text-lg{% if form.errors %} text-red-800{% endif %}"
      >
        Avatar
      </label>
      {% render_field form.image class=widget_class accept="image/*" %} {% include
      "_form_errors.html" with errors=form.image.errors %}
    </div>
    <div class="mb-3">
      {% render_field form.bio class=widget_class placeholder=form.bio.label %} {%
      include "_form_errors.html" with errors=form.bio.errors %}
    </div>
    <div class="mb-3">
      {% render_field form.email class=widget_class placeholder=form.email.label %} {%
      include "_form_errors.html" with errors=form.email.errors %}
    </div>
    <div class="mb-3">
      {% render_field form.password1 class=widget_class %} {% include
      "_form_errors.html" with errors=form.password1.errors %}
    </div>
    <div class="mb-3">
      {% render_field form.password2 class=widget_class %} {% include
      "_form_errors.html" with errors=form.password2.errors %}
    </div>
  </div>

  {% endwith %}
  <div
    class="flex bg-gray-100 rounded-b-lg border border-t-none p-3 justify-end items-center"
  >
    <button
      type="submit"
      class="px-4 py-2 rounded bg-blue-800 text-white hover:bg-blue-600"
    >
      Save Settings
    </button>
  </div>
</form>

templates/users/detail.html
{% extends "base.html" %}
{% load pagination %}
{% block header %}
{{ block.super }}
<div
  class="flex justify-center text-center items-center py-6 mb-3 mx-auto bg-gradient-to-b from-indigo-900 to-indigo-700 text-white w-full"
>
  <div>
    <div class="flex mb-3 justify-center">
      {% include "users/_avatar.html" with user=user_obj size="64" css_class="mr-4" %}
    </div>
    <div class="flex mb-3 justify-center">
      <h1 class="text-5xl">{{ user_obj.username }}</h1>
    </div>
    {% if can_follow %}
    <div class="flex justify-center" id="follow-header">
        {% include "users/_follow.html" %}
    </div>
    {% endif %}
  </div>
</div>
{% endblock header %}
{% block content %}
<div class="border-b flex items-center mb-3">
  <a
    href="{% url 'users:detail' user_obj.username %}"
    class="{% if favorites %}text-gray-500 hover:text-blue-800 pb-3{% else %}text-blue-800 pb-3 border-b-2 border-blue-800{% endif %} mr-6"
  >
    My Articles
  </a>
  <a
    href="{% url 'users:favorites' user_obj.username %}"
    class="{% if favorites %}text-blue-800 pb-3 border-b-2 border-blue-800{% else %}text-gray-500 hover:text-blue-800 pb-3{% endif %}"
  >
    Favorited Articles
  </a>
</div>

{% paginate articles as page_obj %}
{% for article in page_obj.object_list %}
{% include "articles/_article.html" %}
{% endfor %}
{% include "_pagination.html" %}
{% endblock content %}

templates/users/settings.html
{% extends "base.html" %} {% block content %}
<div class="flex justify-center items-center">
  <div class="w-full lg:w-2/3" id="settings-form">
    {% include "users/_settings_form.html" %}
  </div>
</div>

{% endblock content %}